services:
  nginx-php:
    build:
      context: ${XEBRO_ROOT_DIR}/docker/nginx-php/
      dockerfile: Dockerfile
      target: dev
    depends_on:
      php-fpm:
        condition: service_started
    labels:
      traefik.enable: "true"
      traefik.http.routers.api-nginx-tls.entrypoints: websecure
      traefik.http.routers.api-nginx-tls.middlewares: strip-api
      traefik.http.routers.api-nginx-tls.rule: PathPrefix(`${API_PATH_PREFIX}`)
      traefik.http.routers.api-nginx-tls.tls: "true"
      
      traefik.http.routers.api-nginx.entrypoints: web
      traefik.http.routers.api-nginx.middlewares: strip-api
      traefik.http.routers.api-nginx.rule: PathPrefix(`${API_PATH_PREFIX}`)
      
      traefik.http.middlewares.strip-api.stripprefix.prefixes: "${API_PATH_PREFIX}"
    volumes:
      - ${XEBRO_ROOT_DIR}/docker/nginx-php/etc/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ${XEBRO_ROOT_DIR}${XEBRO_PHP_PATH}:/var/www/html:rw
    working_dir: /var/www/html
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    env_file:
      - ${XEBRO_ROOT_DIR}/.env
      - ${XEBRO_ROOT_DIR}/.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    external: true
    name: ${XEBRO_PROJECT_NAME}
